### PR TITLE
Implement psalter

### LINKED ISSUE #39: Implement Psalter
Hi,

I was looking to see if I was able to push a PR to add Psalter to the website but unless I'm mistaken, there seems to already be code for that.

Either I never found out how it's supposed to work or it's not actually working.

Should I go forward and try to implement it?

### PR DESCRIPTION
**Pull request by orklah**
This intend to fix #39

However, I'm pretty sure this is not working but I don't have any idea how to test this.

### CODE REVIEW

**Comment by weirdan** [comment]
You'll need to run `psalm.dev` locally in docker:
* git clone
* composer install
* npm install
* npx webpack
* cp dbconfig.dist.php dbconfig.php
* docker-compose up -d
* access it at http://localhost:8080

Accessing `Articles` section additionally requires `blogconfig.php` in the root folder. I have the following in that file:
```php
return [
    'owner' => 'muglug',
    'repo' => 'psalm/psalm.dev',
    'github_token' => ''
];
```

**Review by weirdan — COMMENTED** [review]
This broke 'fix' button in `Articles` section, and it doesn't seem to have added the fix button in code editor either.

**Comment by orklah** [comment]
> 
> 
> This broke 'fix' button in `Articles` section, and it doesn't seem to have added the fix button in code editor either.

Oh nice, I thought the button was already not functionnal in articles. In now found an article using it. It should be easier to see what's going on :)

Thanks too for the docker procedure, I'll look into that!

**Comment by orklah** [comment]
Ok, it took me a while to get it running correctly on windows, but it's done.

@muglug I have an issue for which I need advice. The OnlineChecker choose manually which severity (suppress, error, info) it wants for each issue type. The problem I have is here:
https://github.com/vimeo/psalm/blob/master/src/Psalm/IssueBuffer.php#L225

If the reporting level is 'info', we will go in that if and we'll never reach that code: https://github.com/vimeo/psalm/blob/master/src/Psalm/IssueBuffer.php#L254

That prevents me for getting results in `IssueBuffer::getFixableIssues` and detecting that psalter could fix things.

The obvious solution would be to put every issue to 'error' but that's not great. I'm wondering why the return false has to be there? https://github.com/vimeo/psalm/blob/master/src/Psalm/IssueBuffer.php#L230

Do you have any hint to how I could progress?

**Comment by muglug** [comment]
Sorry, I’ll get to this tomorrow evening - currently miles away from a computer

**Comment by muglug** [comment]
Thanks, I'll take it from here

**Pull request merged**
