### PR TITLE
Add use_phpdoc_without_magic_call setting

### PR DESCRIPTION
**Pull request by caugner**
The new setting `use_phpdoc_without_magic_call` would enable both [`usePhpDocMethodsWithoutMagicCall`](https://psalm.dev/docs/running_psalm/configuration/#usephpdocmethodswithoutmagiccall) and [`usePhpDocPropertiesWithoutMagicCall`](https://psalm.dev/docs/running_psalm/configuration/#usephpdocpropertieswithoutmagiccall).

Background:

* https://github.com/vimeo/psalm/issues/6023#issuecomment-871598625
* https://github.com/vimeo/psalm/issues/6024#issuecomment-871659083

### CODE REVIEW

**Comment by weirdan** [comment]
Blocked on #55

**Review by weirdan — APPROVED** [review]

**Comment by weirdan** [comment]
@muglug apparently migration failed on deploy. Would you be able to debug this, or grant me permissions to do it myself?

**Comment by weirdan** [comment]
Does it happen right after git pull, or on its own schedule? How big the table is (I.e. could alter take a lot of time)?

**Comment by caugner** [comment]
> According to Phinx it happened on time at 06:45 UTC

@muglug According to the entry in the `phinxlog` table, or according to the output from the deplyoment log? The latter would probably also mentions how long the query took, if I remember correctly.

**Comment by muglug** [comment]
It happens on its own schedule — every five minutes. According to the phinx log the alter took ~1s.

**Comment by weirdan** [comment]
> Given that the column exists now, and provided that the phinxlog table exists (and isn't removed by some magic), merging #56 should probably work now.

Yes.

> It happens on its own schedule — every five minutes. According to the phinx log the alter took ~1s.

Ah, that explains it. I think what happened here was the following: I merged the PR, checked the site and seen it broken. While I was switching to terminal, resetting master and force-pushing it, `composer update` kicked in and applied the migration.

Can we make `composer update` to happen right after code pull, in addition to current schedule?

**Comment by muglug** [comment]
Oh definitely

**Pull request merged**
