### PR TITLE
Exclude `ghostwriter/*` psalm-plugins

### PR DESCRIPTION
**Pull request by ghostwriter**
I unintentionally broke the [plugin ranking system](https://psalm.dev/plugins).

My bad.

It's unfair to other authors.

I'm removing my plugins until there is a new implementation.

### CODE REVIEW

**Comment by weirdan** [comment]
The plugins there ordered by the number of downloads. Is there some (unfair in your opinion) reason why yours are downloaded more than others?

**Comment by ghostwriter** [comment]
I have a custom CI/CD setup on to run on all my repos and it's using that plugin in almost all my private and public projects.

**Comment by ghostwriter** [comment]
I'd like to add,

All of my use-cases are completely legitimate, CI is running on production code for my clients and my dev tools, however the download count does not reflect the **real user** download count as it does for other authors.

**Comment by weirdan** [comment]
> however the download count does not reflect the real user download count 

Pretty much all of those download numbers (as well as downloads for Psalm itself) are heavily skewed by CI servers.

**Comment by ghostwriter** [comment]
Oh… well, then I’ll leave it to you and your team to make the decision of reverting this comment if you choose.

I simply wanted to make sure I made my intentions clear before it was misinterpreted.

**Pull request merged**
