### PR TITLE
Upgrade to PHP 8.1

### PR DESCRIPTION
**Pull request by orklah**

### CODE REVIEW

**Comment by orklah** [comment]
There is no CI here, so I'm not sure what I did will work...

**Review by muglug — APPROVED** [review]

**Comment by muglug** [comment]
psalm.dev itself doesn't use Docker, but updating the image for development is harmless and good.

**Comment by orklah** [comment]
Well, the point was to update psalm.dev itself, where should I look to do that?

**Comment by muglug** [comment]
psalm.dev runs in PHP 7.3, as that's the maximum PHP version supported by the Plesk control panel.

**Comment by muglug** [comment]
I'm updating it to 8.0 now

**Comment by muglug** [comment]
```
x-powered-by: PHP/8.0.12
```

**Pull request merged**
